# MetalLB IP still required for ingestion of Logs from Proxmox Hosts.
# Better use case then having it all go threw ingress for the overhead.

apiVersion: v1
kind: Service
metadata:
  name: luanti-external
  namespace: games
spec:
  selector:
    app: luanti # This label should match your Deployment's pod labels
  ports:
    - protocol: UDP
      port: 30000       # External port for the Service (what you connect to)
      targetPort: 30000 # Internal port of the container deployment
      name: game-port
  type: LoadBalancer 
  loadBalancerIP: 10.104.104.15 #target IP for the service.
# test to see if can direct to container deployment without specifing the port.