# Set to create the service for defining the Traefik External IP
apiVersion: v1
kind: Service
metadata:
  name: ingress-loadbalancer
  namespace: ingress
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.104.104.25"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik  # Matches Traefik Helm chart pods
  ports:
    - name: http
      port: 80
      targetPort: 8000   # Traefik defaults to port 8000 internally for HTTP
    - name: https
      port: 443
      targetPort: 8443   # Traefik defaults to port 8443 internally for HTTPS